[package]
name = "cargo-tai"
version = "0.0.1"
authors = ["Robert Steiner <robertt.debug@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Mobile-testing made easier"
repository = "https://github.com/Robert-Steiner/cargo-tai"
keywords = [
    "test", "mobile", "ios", "android", "cargo"
]
categories = [ "development-tools::cargo-plugins", "development-tools::testing" ]
readme = "../README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
cfg-expr = "0.7.4"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
structopt = "0.3.21"
tai-lib = { path = "../tai-lib", features = ["ios"] }
