name: 'Setup Runner'
description: 'Setup rust'
inputs:
  rust-nightly:
    description: 'Install rust nightly instead of stable'
    default: ""
    required: false
  rust-target:
    description: 'Install an additional rust target'
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Install stable toolchain
      shell: bash
      run: rustup show

    - name: Install nightly toolchain
      if: inputs.rust-nightly != ''
      shell: bash
      run: |
        rustup install ${{ env.RUST_NIGHTLY }}
        rustup component add rustfmt --toolchain ${{ env.RUST_NIGHTLY }}

    - name: Install additional rust target
      if: inputs.rust-target != ''
      shell: bash
      run: rustup target add ${{ inputs.rust-target }}

    - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0
