[package]
name = "tai-lib"
version = "0.0.1"
authors = ["Robert Steiner <robertt.debug@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Mobile-testing made easier"
repository = "https://github.com/Robert-Steiner/cargo-tai"
keywords = [
    "test", "mobile", "ios", "android", "cargo"
]
categories = [ "development-tools::testing" ]
readme = "../README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
cargo_metadata = "0.13.1"
cfg-expr = "0.7.4"
regex = "1.4.5"
serde = "1.0.125"
serde_json = "1.0.64"
once_cell = "1.7.2"
tracing = "0.1"

[target.'cfg(target_os="macos")'.dependencies]
dirs = "3.0.1"
openssl = "0.10.33"
plist = "1.1.0"
simctl = "0.1.1"
tempdir = "0.3.7"
