[package]
name = "tai-lib"
version = "0.0.1"
authors = ["Robert Steiner <robertt.debug@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Mobile-testing made easier"
repository = "https://github.com/Robert-Steiner/cargo-tai"
keywords = [
    "test", "mobile", "ios", "android", "cargo"
]
categories = [ "development-tools::testing" ]
readme = "../README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
base64 = "0.13.0"
cargo_metadata = "0.13.1"
cfg-expr = "0.7.4"
serde = "1.0.126"
serde_bytes = "0.11.5"
serde_json = "1.0.64"
once_cell = "1.8.0"
regex = "1.5.4"
tracing = "0.1.26"
tai-util = { path = "../tai-util" }

# ios feature
tempdir = { version = "0.3.7", optional = true }
openssl = { version = "0.10.34", optional = true }
plist = { version = "1.1.0", optional = true }
simctl = { version = "0.1.1", optional = true }

[features]
default = []
ios = ["tempdir", "openssl", "plist", "simctl"]
