name: Rust-CI

on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup CI
        uses: ./.github/setup
        with:
          rust-nightly: true

      - name: cargo fmt
        run: cargo fmt --all -- --check

  cargo-clippy:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup CI
        uses: ./.github/setup

      - name: cargo clippy
        run: |
          cargo clippy --all-targets -- --deny warnings
          cargo clippy --all-targets --all-features -- --deny warnings

  cargo-test:
    name: cargo-test
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup CI
        uses: ./.github/setup

      - name: Run tests
        env:
          RUSTFLAGS: "-D warnings"
        run: |
          cargo test --workspace --exclude test-project
          cargo test --all-targets --all-features --workspace --exclude test-project

  test-on-ios-simulator:
    runs-on: macos-11
    timeout-minutes: 30
    needs: cargo-test
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup CI
        uses: ./.github/setup
        with:
          rust-target: x86_64-apple-ios

      - name: Start iOS simulator
        run: |
          xcrun simctl create "Test Device" "iPhone 12 Pro" iOS15.2
          xcrun simctl boot "Test Device"

      - name: Install cargo-tai
        run: cargo install --path cargo-tai --debug

      - name: Run iOS test
        working-directory: ${{ github.workspace }}/examples/test-project
        env:
          RUST_LOG: "tai=trace"
        run: cargo-tai tests --target x86_64-apple-ios -r test_txt=./data/test.txt --args -Z,unstable-options,--report-time
